services:
    anix.commastats.listener:
        class: anix\commastats\event\main_listener
        arguments:
            - '@language'
            - '@template'
            - '@config'
            - '@content.visibility'
            - '@pagination'
        tags:
            - { name: event.listener }
